# -*- mode: ruby -*-
# vi: set ft=ruby :

box      = 'precise64daily'
url      = 'http://cloud-images.ubuntu.com/precise/current/precise-server-cloudimg-vagrant-amd64-disk1.box'
hostname = 'snow-dev'
domain   = 'example.com'
ip       = '192.168.0.2'
ram      = '2048'

chef_server_url = "https://backend.logosxchange.com"
role = "solo-logos"
chef_path = "../../chef/"
validation_client_name = "validator-dev"
validation_key_path = chef_path + ".chef/validator.dev.pem"
encrypted_data_bag_secret_key_path = chef_path + '.chef/encrypted_data_bag_secret'
environment = "dev"
node_name = hostname

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.box_url = url
  
  config.vm.hostname = hostname
  config.vm.network :forwarded_port, guest: 8010, host: 8010
  config.vm.network :forwarded_port, guest: 9001, host: 9001
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :private_network, ip: ip
  config.vm.synced_folder ".", "/vagrant"
  config.omnibus.chef_version = :latest
  
  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.customize [
    'modifyvm', :id,
    '--name', hostname,
    '--memory', ram
    ]
  end

  config.vm.provision "chef_client" do |chef|
    chef.chef_server_url = chef_server_url
    chef.validation_client_name = validation_client_name
    chef.validation_key_path = validation_key_path
    chef.encrypted_data_bag_secret_key_path = encrypted_data_bag_secret_key_path
    chef.node_name = node_name
    chef.environment = environment
    chef.add_role role
  end
  
  
end
