module.exports = {
    MarketsView: require('./MarketsView'),
    MarketView: require('./MarketView'),
    HeaderView: require('./HeaderView'),
    UserAccountsView: require('./UserAccountsView'),
    UserOrdersView: require('./UserOrdersView'),
    UserTransactionsView: require('./UserTransactionsView'),
    CreateOrderView: require('./CreateOrderView'),
    WithdrawBTCView: require('./WithdrawBTCView'),
    DepositBTCView: require('./DepositBTCView'),
    WithdrawLTCView: require('./WithdrawLTCView'),
    DepositLTCView: require('./DepositLTCView'),
    RouteNotFoundView: require('./RouteNotFoundView'),
    ErrorView: require('./ErrorView'),
    LoginView: require('./LoginView'),
    HomeView: require('./HomeView'),
    TransferView: require('./TransferView'),
    RippleOutView: require('./RippleOutView'),
    RegisterView: require('./RegisterView')
}
