---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.10
  - name: ubuntu-13.04
  - name: centos-6.4

suites:
  - name: append
    run_list: ['recipe[fake::append]']
  - name: append_existing
    run_list: ['recipe[fake::append_existing]']
  - name: create
    run_list: ['recipe[fake::create]']
  - name: create_if_missing
    run_list: ['recipe[fake::create_if_missing]']
  - name: default
    run_list: ['recipe[fake::default]']
  - name: options
    run_list: ['recipe[fake::options]']
