require('shelljs/global')

var format = require('util').format

function execOrDie(cmd) {
    var result = exec(cmd, { silent: false })
    if (result.code === 0) return
    console.error(cmd + ' status ' + result.code)
    console.error(result.output)
    process.exit(result.code)
}

function publishTo(host) {
    execOrDie('npm pack')

    var stamp = +new Date()
    , name = require('./package.json').name
    , version = require('./package.json').version
    , fn = format('%s-%s.tgz', name, version)

    execOrDie(format('scp %s %s:/home/ubuntu/snow-workers/app/%s-%s.tgz', fn, host, name, stamp))
    execOrDie(format('ssh %s cd snow-workers/app ; ./deploy.sh %s', host, stamp))
    execOrDie('rm ' + fn)
}

task('pp', ['publish-production'])
task('publish-production', function() {
    publishTo('10.0.1.213')
})
